services:
  context-broker:
    image: node:lts-alpine
    command: sh -c "npm install && nodemon src/index.js"
    working_dir: /home/node/app
    volumes:
      - ../context-broker/:/home/node/app/

    ports:
      - 8000:8000
    environment:
      - CONTEXT_BROKER_PORT=8000
      - MONGO_HOST=mongo
      - DB_NAME=solar

  # record-engine:
  #   image: record-engine
  #   ports:
  #     - 8001:8001
  #   environment:
  #     - PORT=8001
  #     - DB_URI=mongodb://mongo:27017
  #     - DB_NAME=solar
  #     - DB_TIMEOUT_MS=10000

  mqtt-agent:
    image: node:lts-alpine
    command: sh -c "npm install && nodemon src/index.js"
    working_dir: /home/node/app
    volumes:
      - ../mqtt-agent/:/home/node/app/

    ports:
      - 8003:8003
    environment:
      - MQTT_AGENT_PORT=8003
      - MQTT_BROKER_HOST=mqtt
      - CONTEXT_BROKER_HOST=context-broker
      - CONTEXT_BROKER_PORT=8000
      - REDIS_HOST=redis

  # monitoring-backend:
  #   image: monitoring-backend
  #   ports:
  #     - 8002:8002
  #   environment:
  #     - PORT=8002
  #     - SECRET=topsecret
  #     - DB_URI=mongodb://mongo:27017
  #     - DB_NAME=solar
  #     - DB_TIMEOUT_MS=10000
  #     - CONTEXT_BROKER_URL=http://context-broker:8000
  #     - RECORD_ENGINE_URL=http://record-engine:8001

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dev-mongo-data:/data/db

  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
    # image: emqx/emqx

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  dev-mongo-data:
